name: Manual PreRelease Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Get version, short commit hash, and date
        id: vars
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          COMMIT_ID=$(git rev-parse --short=5 HEAD)
          TODAY=$(date +'%d-%m-%Y')
          NEW_VERSION="${CURRENT_VERSION}-${COMMIT_ID}-${TODAY}"

          echo "version=$NEW_VERSION" >> "$GITHUB_OUTPUT"

      - name: Update version
        run: |
          npm version ${{ steps.vars.outputs.version }} --no-git-tag-version

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Publishing version ${{ steps.vars.outputs.version }}"
          npm publish --tag dev
