name: Manual Release Publish

on:
  workflow_dispatch:

jobs:
  get-next-version:
    uses: ./.github/workflows/get-next-version.yml
  release-publish:
    needs: get-next-version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Update version
        id: update-version
        run: |
          npm version ${{ needs.get-next-version.outputs.version }} --no-git-tag-version

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Publishing version ${{ steps.update-version.outputs.version }}"
          npm publish