name: Manual Release Publish

on:
  workflow_dispatch:

jobs:
  release-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Get current version from package.json
        id: get_version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "current_version=$CURRENT_VERSION" >> "$GITHUB_OUTPUT"

      - name: Calculate new version
        id: bump_version
        run: |
          VERSION=${{ steps.get_version.outputs.current_version }}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          if [ "$MINOR" -eq 9 ]; then
            # minor=9 → bump major, reset minor and patch
            NEW_MAJOR=$((MAJOR + 1))
            NEW_VERSION="${NEW_MAJOR}.0.0"
          else
            # bump minor, reset patch
            NEW_MINOR=$((MINOR + 1))
            NEW_VERSION="${MAJOR}.${NEW_MINOR}.0"
          fi

          echo "new_version=$NEW_VERSION" >> "$GITHUB_OUTPUT"

      - name: Update version
        run: |
          npm version ${{ steps.bump_version.outputs.new_version }} --no-git-tag-version

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish
